### ISSUE TITLE
Support for Live Videos

### ISSUE THREAD

**Issue by DavidBerdik** [xxcodianxx/youtube-dl-web#18]
Would it be possible to add support for live videos? I am asking because I am interested in using this server for streaming audio from YouTube without downloading it via the `http://localhost/api/dl/<VIDEO ID>?f=bestaudio` endpoint. It works perfectly except for the lack of live video support!

**Comment by xxcodianxx** [comment]
Alright, I will look into this, it seems yt-dlp supports live videos, so I'll get back to you soon.

**Comment by DavidBerdik** [comment]
That would be great! Thank you!

**Comment by xxcodianxx** [comment]
@DavidBerdik I tested various things with live videos, and they generally behave weird. 

- yt-dlp does not actually provide distinct audio & video streams, it just labels everything as "video only", though there is sound...
- all "video only" streams (which actually contain audio as well) are unnamed
- neither of the "bestaudio" and "bestvideo" formats work, though "best" works properly!

Now, there was a bug in the metadata getting API **that should be fixed by** 3ce6a2443cf4ef4bab85340c1618a533b508e6b2.

Since `bestaudio` won't work, I suggest pulling the whole thing and just stripping the video off of it. Sorry there is no easy way to get audio-only. I'm considering reworking this project majorly with better organization & support for live videos, though I can't promise anything.

Hope this helps! 

PS. I see you're referencing the /api/dl endpoint instead of just talking to the server directly. Note that /api passes through nginx, you can reference the API server's /dl endpoint directly to skip some overhead!

**Comment by DavidBerdik** [comment]
@xxcodianxx Thanks for looking in to this! If time permits, perhaps I will mess around with trying to make it work myself, but for now, I'll just accept that I can't handle live streams for my use case. No big deal. 🙂

As for the API endpoint, thanks for pointing that out! I don't know if anyone has any use for it aside from me, but I have made a stripped-down version of the code available [here](https://github.com/DavidBerdik/YouTube-Stream-Repeater). It's pretty much identical except for the removal of the web UI.
